apiVersion: batch/v1
kind: Job
metadata:
  generateName: slack-notification-
  namespace: test
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: notify
        image: technosophos/slack-notify
        env:
          - name: SLACK_TITLE
            value: 'ArgoCD test notification'
          - name: SLACK_MESSAGE
            value: 'NOOOO, THE JOB HAS FAILED. WE ARE DOOMED!!!!!!'
        envFrom:
          - secretRef:
              name: slacksecret
