apiVersion: batch/v1
kind: Job
metadata:
  generateName: slack-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: notify
        image: technosophos/slack-notify
        env:
          - name: SLACK_TITLE
            value: 'ArgoCD test notification'
          - name: SLACK_CHANNEL
            value: 'team-deployments'
          - name: SLACK_MESSAGE
            value: 'Test from Kubernetes job'
        envFrom:
          - secretRef:
              name: slacksecret
